### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by Stoatwblr** [tomolimo/timezones#1]
It would be a good idea to mention in readme.md that if "clicking on enable" doesn't work, then scripts/updatedb needs to be run.

Also that apc.enable_cli may need to be enabled in php.ini (or php.ini.d/{something})

**Comment by Stoatwblr** [comment]
Also: the plugin pulled down from here is identifying itself as 1.3.0, not 2.0.0

**Comment by tomolimo** [comment]
From where?

**Comment by tomolimo** [comment]
Could you please give the URL you used to download the plugin?

**Comment by Stoatwblr** [comment]
https://github.com/tomolimo/timezones/archive/master.zip

**Comment by tomolimo** [comment]
Thank you,
I see this is the link from the GLPi plugin pages, and I've not updated it, sorry for that.
The v2.0.0 is here: https://github.com/tomolimo/timezones/releases

**Comment by tomolimo** [comment]
And don't forget to rename the extracted timezone-2.0.0 folder to "timezones" in your GLPi plugins folder.

**Comment by tomolimo** [comment]
Regarding the apc.enable_cli, I don't use this extension at all. So I'm not going to mention this in the wiki.
Regarding the 'enable' behavior: I agree, something is missing either in the wiki, either in the source code to be able to view the right information when needed.
Thank you to have report these issues.
Regards,
Tomolimo
