### ISSUE TITLE
Timezone  Update not going 2.1.2

### ISSUE THREAD

**Issue by Tamilvel** [tomolimo/timezones#10]
error altering glpi_plugin_timezones_usersTable 'helpdesk.glpi_plugin_timezones_users' doesn't exist

throwing while upgrading the Plugin from older version

**Comment by tomolimo** [comment]
Hello,
What's your GLPI configuration?
From which version are you upgrading?
Thank you,
regards,
Tomolimo

**Comment by tomolimo** [comment]
Could you post the logs content php and sql?
thank you
regards,
Tomolimo

**Comment by tomolimo** [comment]
Which version of MySQL do you use?

**Comment by tomolimo** [comment]
Any news?

**Comment by Tamilvel** [comment]
HI
My GLPI 0.9.1.2 to 9.1.3

earlier with glp 9.1.1 working fine.

now it throwing the error

regards
Tamilvel

**Comment by tomolimo** [comment]
Hello,
From which version of timezones plugin are you upgrading?
Which MySQL version are you using?
Could you post the log files content for php and sql errors?
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Closed this issue as I got no answer.
Please fell free to re-open it with more information like requested.
Regards
Tomolimo
