### ISSUE TITLE
Integrate timezones in calendars

### ISSUE THREAD

**Issue by lexcorp** [tomolimo/timezones#11]
Hi Tomolimo,

This is a suggestion: Enable the option to select a time zone during the creation of a calendar.

This would allow them to handle different schedules and their respective time zones.

![captura](https://user-images.githubusercontent.com/5751288/28598345-8a98822e-7168-11e7-9317-4e9ebd90fa35.JPG)

![captura2](https://user-images.githubusercontent.com/5751288/28598347-8e22b70c-7168-11e7-9749-e797f9a79092.JPG)

**Comment by tomolimo** [comment]
Hello
Thank you for suggestion.
Could you give a complete 'use case'? So that I'll be able to understand clearly the need.
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @lexcorp 
I'm closing this issue as I got no news about it.
Feel free to re-open it if needed.
Thank you,
Regards,
Tomolimo
