### ISSUE TITLE
Integrate timezones in SLA's and Rules

### ISSUE THREAD

**Issue by lexcorp** [tomolimo/timezones#12]
Hello Tomolimo, this is another suggestion:

Integrate timezones in SLA's and Rules creation.

**Comment by tomolimo** [comment]
Hello,
One of my colleagues did some tests with SLA and rules, and it seems to be OK with Timezones plugin.
But of course, if you give me 'use cases', I'll make tests of them.
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @lexcorp 
I'm closing this issue as I got no news about it.
Feel free to re-open it if needed.
Thank you,
Regards,
Tomolimo
