### ISSUE TITLE
Compatibility with GLPI 9.2

### ISSUE THREAD

**Issue by AircraftRu** [tomolimo/timezones#14]
Hello,
I wait the compatibility with GLPI 9.2

![glpi - timezones](https://user-images.githubusercontent.com/17082164/30856646-ae579e4a-a2c1-11e7-8a57-8749204d9ee5.png)

**Comment by tomolimo** [comment]
Hello,
Before new version, you can change the prototype to reflect the new one. Or you may comment out the function. This function is only to get timezone info in log files.
Regards
Tomolimo

**Comment by AircraftRu** [comment]
Ok. but I didn't understand you. What is the prototype?
Will you make compatibility?

**Comment by tomolimo** [comment]
Don't worry with my comment, I'll do it of course :smile:

**Comment by tomolimo** [comment]
See: https://github.com/tomolimo/timezones/releases/tag/2.2.0
