### ISSUE TITLE
SLA added automatically even though no SLA defined 

### ISSUE THREAD

**Issue by roshanroche** [tomolimo/timezones#16]
Hi @tomolimo ,
i installed timezone plugin on glpi 9.2.4 by following ur wiki. it installed without any error and activated,
i created users under 2 different entities with different timezone.
since activation , when i create a ticket the SLAs added for both time to own and time to resolve ( both SLA and OLA ) as 19-01-2038 07:14 for all the tickets created.
![image](https://user-images.githubusercontent.com/22425503/41837940-05477336-7870-11e8-998c-60eb54527f1a.png)
![image](https://user-images.githubusercontent.com/22425503/41837962-0e5eb696-7870-11e8-8fe0-3e6330da3157.png)
for all the tickets same time it shows
![image](https://user-images.githubusercontent.com/22425503/41838013-36993ba4-7870-11e8-98cd-983ccf399094.png)

System Info : Centos 7.5 MariaDB 10.2.15 , tried both on glpi 9.1.7 and 9.2.4 same issue
something related to database?

**Comment by tomolimo** [comment]
Hello @roshanroche 
Did you set the timezone for the server?
Thank you
Regards,
Tomolimo

**Comment by roshanroche** [comment]
hi @tomolimo ,
i followed the steps from ur wiki. where on server i have to set the timezone?
u mean php.ini? or is there any parameter in mariadb to do that?

**Comment by tomolimo** [comment]
Yes, it's in the php.ini

**Comment by tomolimo** [comment]
it's described in the wiki here: https://github.com/tomolimo/timezones/wiki/Requirements

**Comment by roshanroche** [comment]
yea i have done that. on php.ini.

**Comment by tomolimo** [comment]
good, then if you check the phpinfo(), you may get something like following in the timezone section:

> date

> date/time support  enabled  
> "Olson" Timezone Database Version  2015.3  
> Timezone Database  external  
> Default timezone  Europe/Paris  

could you paste this info here?

**Comment by roshanroche** [comment]
date/time support | enabled
-- | --
timelib version | 2017.06
"Olson" Timezone Database Version | 0.system
Timezone Database | internal
Default timezone | Europe/Paris

**Comment by tomolimo** [comment]
Hello @roshanroche 
I made a test on my 9.2.4 and I got no problem:

this user in Europe/Paris TZ

![image](https://user-images.githubusercontent.com/7569958/41842445-135f1cb2-786b-11e8-85bf-97da38ba7382.png)


and

this user in America/Detroit TZ

![image](https://user-images.githubusercontent.com/7569958/41842213-7e17ab1a-786a-11e8-8257-5f7b284aea84.png)


Could you provide me the complete step list to be able to reproduce your issue?
Do you have any other plugins that would set these fields?

Thank you,
Regards,
Tomolimo

**Comment by roshanroche** [comment]
Hi @tomolimo ,
is this issue related to Mariadb 10 version?
or is it related to something with this https://fossbytes.com/year-2038-problem-linux-unix/
it is happening on 9.1.7 version also.
because i feel i have followed every step which u have mentioned in ur wiki. and it shows me the tz properly for users.
it a fresh install of 9.2.4 without any plugins. 

i found this error in sql
SQL: INSERT INTO glpi_plugin_timezones_tasks_localtimes SELECT NULL, 'ChangeTask' as items_type, id as items_id, `begin`, `end` FROM glpi_changetasks;
  Error: Column count doesn't match value count at row 1
  Backtrace :
  plugins/timezones/hook.php:178                     
  plugins/timezones/hook.php:81                      convertDB()
  inc/plugin.class.php:731                           plugin_timezones_install()
  front/plugin.form.php:48                           Plugin->install()

**Comment by roshanroche** [comment]
Hi ,
i also found under glpi_users table following entries
![image](https://user-images.githubusercontent.com/22425503/41847330-ae821ed2-788a-11e8-8129-1d1601bc25e2.png)

and under glpi_tickets table this

![image](https://user-images.githubusercontent.com/22425503/41847398-e47fa6e4-788a-11e8-81c9-b30e7a67e2e6.png)

**Comment by tomolimo** [comment]
thank you for your investigations,
could you also check the structure of the glpi_users and glpi_tickets tables? Especially the fields date fields?
The type should be TIMESTAMP.

Could it be linked to the way MariaDB manages DATETIME field conversion to TIMESTAMP field?

**Comment by roshanroche** [comment]
![image](https://user-images.githubusercontent.com/22425503/41847760-34bd58c6-788c-11e8-89e8-3015c108c60b.png)
![image](https://user-images.githubusercontent.com/22425503/41847773-45c72e3a-788c-11e8-9df7-56d7f945925d.png)
![image](https://user-images.githubusercontent.com/22425503/41847807-684b2f1a-788c-11e8-8cbb-4d471fbf9915.png)

**Comment by tomolimo** [comment]
Thank you,

I'll make a test using MariaDB, and I'll keep you informed,

Thank you,
Regards,
Tomolimo

**Comment by roshanroche** [comment]
@tomolimo ,
i see the default value for these fields is 
![image](https://user-images.githubusercontent.com/22425503/41847908-c51b747a-788c-11e8-998a-e8482feb323b.png)
is that something related?
i recall last time i had installed this plugin on 9.1.6 with maria db 5.4 version. i dont remember if i faced same issue or i noticed.
this time around this installation was on MD 10 version.

**Comment by tomolimo** [comment]
Yes this default value is the MAX date that can be used in a TIMESTAMP field.
But I don't understand why this default value has been set...

**Comment by roshanroche** [comment]
@tomolimo ,
thanks for ur time and patience. if i come across any related information ill inform u at the same time.

**Comment by roshanroche** [comment]
@tomolimo ,
funny thing is i resigned both tables and reset default value of the fields to NULL , and the SLA issue doesnt happen.

**Comment by tomolimo** [comment]
Hello @roshanroche 
I'm closing this issue as it seems tha tit was related to MariaDB default value for timestamp fields.
Thank you
Regards,
Tomolimo
