### ISSUE TITLE
Time zone table

### ISSUE THREAD

**Issue by satyan01** [tomolimo/timezones#2]
Hello,

I am sorry but not understand the procedure.

Do I have to create a time_zone table in glpi ?

Thank you for your answer

**Comment by tomolimo** [comment]
Hello 
The plugin will create its own tables, but you must cope with the time zones of PHP, and with the time zones of mysql. 
Regards 
Tomolimo

**Comment by tomolimo** [comment]
See https://github.com/tomolimo/timezones/wiki/Requirements

**Comment by satyan01** [comment]
I am sorry but I don't understand what I have to do

**Comment by tomolimo** [comment]
What don't you understand?

**Comment by tomolimo** [comment]
Is it the mySQL configuration, or PHP configuration?

**Comment by satyan01** [comment]
Both

**Comment by tomolimo** [comment]
What is your GLPi configuration, version, OS, PHP and DB server?

**Comment by satyan01** [comment]
windows 2012r2 / glpi 9.1 / php 7.04 / mariadb 10.1

**Comment by tomolimo** [comment]
ok, thank you, 
I'm going to give you detailed instructions, about the configuration steps, are you ready?

**Comment by satyan01** [comment]
yes thank you very much

**Comment by tomolimo** [comment]
ok, let's start with PHP:
goto: https://pecl.php.net/package/timezonedb/2016.8/windows
download "7.0 Non Thread Safe (NTS) x64" if you use IIS on Windows x64
or
download "7.0 Thread Safe (TS) x64" if you use Apache x64 or download "7.0 Thread Safe (TS) x86" if you use Apache x86

**Comment by satyan01** [comment]
done

**Comment by tomolimo** [comment]
what did you download?
what is your web server?

**Comment by satyan01** [comment]
download "7.0 Non Thread Safe (NTS) x64" if you use **IIS** on Windows x64

**Comment by tomolimo** [comment]
ok,
then now:
copy the php_timezonedb.dll into the ext folder of your PHP 7
and edit your php.ini file and add 'extension=php_timezonedb.dll'

**Comment by satyan01** [comment]
done

**Comment by tomolimo** [comment]
open a cmd box, and type:
`php --ri timezonedb`
and give me back the result

**Comment by satyan01** [comment]
enabled 
database version 2016.8

**Comment by tomolimo** [comment]
good
let's go to mysql config now:

you must check the type of the table 'time_zone' in databse 'mysql' in MariaDB, it should be either MyISAM or either 'InnoDB', give me back this?

**Comment by satyan01** [comment]
myisam

**Comment by tomolimo** [comment]
ok, then goto http://dev.mysql.com/downloads/timezones.html, and download timezone_2016h_posix.zip

**Comment by satyan01** [comment]
done

**Comment by tomolimo** [comment]
then stop your db server
unzipped the previously downloaded files into the mysql folder (it should replace files with the same names, to be sure, backup these files before doing the replace).
restart the db server

**Comment by satyan01** [comment]
done

**Comment by satyan01** [comment]
it seems glpi timezone plugins is ready to install

**Comment by tomolimo** [comment]
mysql (or mariadb) and php are now up to date with timezone infos

**Comment by satyan01** [comment]
ok

**Comment by satyan01** [comment]
other thing : I have this message in glpi

Installing the "apcu-bc" extension may improve GLPI performance

**Comment by satyan01** [comment]
'dbupdate' script must be executed before enabling this plugin!
see: See wiki

**Comment by tomolimo** [comment]
for apcu-bc, you must post on glpi forum

**Comment by tomolimo** [comment]
for dbupdate, just follow the wiki: https://github.com/tomolimo/timezones/wiki/Installation

**Comment by satyan01** [comment]
after update I have this page

ALTER TABLE `glpi_alerts` MODIFY COLUMN `date` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ; --> done ALTER TABLE `glpi_apiclients` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `app_token_date` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_authldaps` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_authmails` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_blacklistedmailcontents` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_blacklists` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_budgets` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_budgettypes` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_calendars` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_cartridgeitems` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_cartridgeitemtypes` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_cartridges` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_changes` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `solvedate` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `closedate` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `due_date` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `begin_waiting_date` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_changetasks` MODIFY COLUMN `date` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `begin` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `end` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_changevalidations` MODIFY COLUMN `submission_date` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `validation_date` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_computerantiviruses` MODIFY COLUMN `date_expiration` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_computerdisks` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_computermodels` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_computers` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_computertypes` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_computervirtualmachines` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_consumableitems` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_consumableitemtypes` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_consumables` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_contacts` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_contacttypes` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_contracts` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_contracttypes` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_crontasklogs` MODIFY COLUMN `date` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ; --> done ALTER TABLE `glpi_crontasks` MODIFY COLUMN `lastrun` TIMESTAMP NULL DEFAULT NULL COMMENT 'last run date', MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_devicecases` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_devicecasetypes` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_devicecontrols` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_devicedrives` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_devicegraphiccards` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_deviceharddrives` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_devicememories` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_devicememorytypes` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_devicemotherboards` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_devicenetworkcards` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_devicepcis` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_devicepowersupplies` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_deviceprocessors` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_devicesoundcards` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_documentcategories` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_documents` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_documents_items` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_documenttypes` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_domains` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_entities` MODIFY COLUMN `max_closedate` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_events` MODIFY COLUMN `date` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_fieldblacklists` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_fieldunicities` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_filesystems` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_fqdns` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_groups` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_holidays` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_infocoms` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `decommission_date` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_interfacetypes` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_ipnetworks` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_itilcategories` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_knowbaseitemcategories` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_knowbaseitems` MODIFY COLUMN `date` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `begin_date` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `end_date` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_links` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_locations` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_logs` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_mailcollectors` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_manufacturers` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_monitormodels` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_monitors` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_monitortypes` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_netpoints` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_networkequipmentfirmwares` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_networkequipmentmodels` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_networkequipments` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_networkequipmenttypes` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_networknames` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_networkportaggregates` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_networkportaliases` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_networkportdialups` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_networkportethernets` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_networkportfiberchannels` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_networkportlocals` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_networkports` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_networkportwifis` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_networks` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_notepads` MODIFY COLUMN `date` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_notifications` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_notificationtemplates` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_notimportedemails` MODIFY COLUMN `date` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ; --> done ALTER TABLE `glpi_operatingsystemarchitectures` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_operatingsystems` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_operatingsystemservicepacks` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_operatingsystemversions` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_peripheralmodels` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_peripherals` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_peripheraltypes` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_phonemodels` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_phonepowersupplies` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_phones` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_phonetypes` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_planningrecalls` MODIFY COLUMN `when` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_plugin_badges_badges` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_plugin_badges_requests` MODIFY COLUMN `affectation_date` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `return_date` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_plugin_behaviors_configs` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_plugin_certificates_certificates` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_plugin_connections_connections` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_plugin_databases_databases` MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL ; --> done ALTER TABLE `glpi_plugin_datainjection_models` MODIFY COLUMN `date_mod` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ; --> done ALTER TABLE `glpi_plugin_escalade_histories` MODIFY COLUMN `date_mod` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ; --> done ALTER TABLE `glpi_plugin_formcreator_formanswers` MODIFY COLUMN `request_date` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ; --> done ALTER TABLE `glpi_plugin_formcreator_issues` MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL ; --> error when applying 'glpidb91.glpi_plugin_formcreator_issues' is not BASE TABLE

**Comment by satyan01** [comment]
ALTER TABLE `glpi_plugin_formcreator_issues` MODIFY COLUMN `date_creation` TIMESTAMP NULL DEFAULT NULL , MODIFY COLUMN `date_mod` TIMESTAMP NULL DEFAULT NULL ; --> error when applying 'glpidb91.glpi_plugin_formcreator_issues' is not BASE TABLE

**Comment by tomolimo** [comment]
As I don't use formcreator, could you send me the definition of the table?

**Comment by satyan01** [comment]
what is the or where is the definition

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/19930035/bca65d32-a106-11e6-8234-b189cc94d827.png)

**Comment by tomolimo** [comment]
it's not a table, it's a view

**Comment by satyan01** [comment]
how to skip this error, because in glpi i have  'dbupdate' script must be executed before enabling this plugin!
see: See wiki

and I can't use the plugin

**Comment by tomolimo** [comment]
I'm doing an investigation

**Comment by satyan01** [comment]
thx

**Comment by satyan01** [comment]
2016-11-02 14:11:43 [854@UNGSRVGVA118]
  **\* PHP Notice(8): Undefined index: Create Table
  Backtrace :
  plugins\timezones\scripts\dbupdate.php:21

**Comment by tomolimo** [comment]
Could you test with a new dbupdate.php?
I just made a new version to take into account such cases where a view is used in glpi.
Download the new file here : https://github.com/tomolimo/timezones/blob/master/scripts/dbupdate.php
and replace the current one in scripts folder
and relaunch it like previously

**Comment by satyan01** [comment]
it works, however, What I have to do after that

**Comment by tomolimo** [comment]
just enable the plugin

**Comment by satyan01** [comment]
I have installed this plugin to fix an issue, when Singapore user create a ticket the sla starts at 2am while our working hour are 8am to 6:30pm.

Normally the sla should start at 8am

**Comment by tomolimo** [comment]
This plugin has never been tested for SLA, then thank you for any issue you may find about this

**Comment by satyan01** [comment]
maybe you could add on the wiki to modify timezone for users at the end of installation

Thank you very much for your great help !
