### ISSUE TITLE
internal error 500

### ISSUE THREAD

**Issue by satyan01** [tomolimo/timezones#3]
Since installation, I have regularly internal error 500, at each time I have to close the chrome page and open new one

**Comment by tomolimo** [comment]
Could you look into the logs and give me back any info?

**Comment by tomolimo** [comment]
Could you also test disabling the timezones plugin and/or the formcreator plugin?

**Comment by tomolimo** [comment]
Could you also give any information in order to reproduce this problem?

**Comment by satyan01** [comment]
I could not active timezone plugin anymore in glpi

no log in php

**Comment by tomolimo** [comment]
same error, or something else?

**Comment by satyan01** [comment]
no error just impossible to enable the plugin

**Comment by satyan01** [comment]
maybe I can uninstall an install

**Comment by tomolimo** [comment]
see : https://github.com/tomolimo/timezones/wiki/Very-important-note

**Comment by satyan01** [comment]
I have uninstall and install, but ask again to updatedb, i have done it, reactivate it and error 500 many times

**Comment by tomolimo** [comment]
could you describe the exact steps by steps the way to reproduce the error 500?

**Comment by satyan01** [comment]
I had to uninstall it because of error 500

**Comment by satyan01** [comment]
I went to a user module to check his time zone and when I clicked on time zone tab error 500

**Comment by tomolimo** [comment]
If you want to be helped, you must tell me exactly what you did (step by step) and the results

**Comment by satyan01** [comment]
I did it : I have uninstall and install, but ask again to updatedb, i have done it, reactivate it 
I went to a user module to check his time zone and when I clicked on time zone tab error 500

**Comment by tomolimo** [comment]
ok thank you, any error in log files?

**Comment by satyan01** [comment]
nothing

**Comment by tomolimo** [comment]
could you disable the formcreator plugin?
and test again?

**Comment by satyan01** [comment]
it works but it does not do at each time, I have to wait and see

**Comment by satyan01** [comment]
and I need to use form creator...

**Comment by tomolimo** [comment]
yes, but this is a good clue, I'm going to investigate in this direction

**Comment by tomolimo** [comment]
which version of formcreator do you use?

**Comment by satyan01** [comment]
I have disabled it because I have often error 500

**Comment by tomolimo** [comment]
which version of formcreator do you use?

**Comment by satyan01** [comment]
Forms   0.90-1.4-beta4

**Comment by tomolimo** [comment]
where did you get this version?
it's not an official release, I've downloaded the official one and I have no problem with it (https://github.com/pluginsGLPI/formcreator/releases/latest)

**Comment by tomolimo** [comment]
close issue as not relevant with timezones plugin as used Forms plugin is in beta status.
feel free to re-open when Forms plugin will be in official status and after a new test.

**Comment by satyan01** [comment]
form creator updated and same issue

**Comment by tomolimo** [comment]
To which version?

**Comment by satyan01** [comment]
Formulaires 0.90-1.3.4

**Comment by tomolimo** [comment]
Could you then send to me your database in a zipped file?
go to https://webchat.freenode.net/ and I'll give you my email address

**Comment by satyan01** [comment]
I need nickname and channel

**Comment by tomolimo** [comment]
Nickname is yours and channel is #glpi, but I left, so will see tomorrow

-------- Original message --------
From: Yannick
Date:03/11/2016 17:12 (GMT+01:00)
To: tomolimo/timezones
Cc: "Moron, Olivier" , State change
Subject: Re: [tomolimo/timezones] internal error 500 (#3)

I need nickname and channel

**Comment by satyan01** [comment]
i am connected

**Comment by tomolimo** [comment]
Hello,
Before sending DB, I've new questions,
1) Could you tell me the complete plugin list you are using? Which versions? Official releases or from github master branches?
2) Same questions for GLPi.
Thank you,
regards,
Tomolimo

**Comment by satyan01** [comment]
Hello

1 - 
fields               Name: Additionnal fields             Version: 1.3.1      State: Enabled
    news                 Name: Alerts                         Version: 0.90-1.3   State: Not installed
    badges               Name: Badges                         Version: 2.2.0      State: Enabled
    behaviors            Name: Behaviours                     Version: 1.1        State: Enabled
    certificates         Name: Certificates                   Version: 2.2.0      State: Enabled
    dashboard            Name: Dashboard                      Version: 0.7.7      State: Enabled
    escalade             Name: Escalades                      Version: 2.1.0      State: Enabled
    formcreator          Name: Formulaires                    Version: 0.90-1.3.4 State: Enabled
    fpsoftware           Name: FP Software                    Version: 1.1.0      State: Enabled
    fusioninventory      Name: FusionInventory                Version: 9.1+1.0    State: Enabled
    genericobject        Name: Gestion d'objets               Version: 2.4.0      State: Not activated
    datainjection        Name: Injection de fichiers          Version: 2.4.2      State: Enabled
    addressing           Name: IP Adressing                   Version: 2.4.0      State: Enabled
    reports              Name: Reports                        Version: 1.9.1      State: Enabled
    reservation          Name: Réservation                    Version: 1.3.2      State: Enabled
    simcard              Name: Sim cards management           Version: 1.4.2      State: Enabled
    manufacturersimports Name: Suppliers imports              Version: 1.9.0      State: Enabled
    timelineticket       Name: Timeline of tickets            Version: 0.90+1.0   State: Enabled
    timezones            Name: Timezones                      Version: 2.0.0      State: Not activated
    webapplications      Name: Web applications               Version: 2.1.1      State: Enabled
    webservices          Name: Web Services                   Version: 1.6.0      State: Enabled

official releases normally

GLPI 9.1 official release

**Comment by tomolimo** [comment]
thank you,
then let's try to trace down your http error 500:
Do you know how to activate the 'Failed Request Tracing' in IIS?

**Comment by satyan01** [comment]
already activated

**Comment by tomolimo** [comment]
Activated and a special rule for http error 500?

**Comment by satyan01** [comment]
no content just the module

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/19997723/c9a29038-a268-11e6-8a5c-99edb496783b.png)

**Comment by tomolimo** [comment]
ok,
see this:
![image](https://cloud.githubusercontent.com/assets/7569958/19997713/bf42c69e-a268-11e6-8ea5-44495f84d65d.png)

keep in mind the 'Directory' folder in which you'll find the traces

then

try to reproduce the error

**Comment by tomolimo** [comment]
it could be better also to enlarge the trapped error codes like this:
![image](https://cloud.githubusercontent.com/assets/7569958/19997802/35b2a4de-a269-11e6-91df-7048cda11f74.png)

**Comment by satyan01** [comment]
I have a lot of error 
![image](https://cloud.githubusercontent.com/assets/15144026/19999626/cf05af78-a273-11e6-8281-3fcb6abb8917.png)

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/19999657/f550922e-a273-11e6-9713-7d26cb09846e.png)

**Comment by tomolimo** [comment]
click on 'view trace' to drill down

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/19999720/401679ae-a274-11e6-948f-9e237ffccae8.png)

**Comment by tomolimo** [comment]
expand also the line 48

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/19999795/afb5fa32-a274-11e6-9cd3-c29b501254b3.png)

**Comment by tomolimo** [comment]
try this: https://forums.iis.net/t/1228496.aspx

**Comment by satyan01** [comment]
already installed 
![image](https://cloud.githubusercontent.com/assets/15144026/19999936/4f7d0cfe-a275-11e6-86fc-977c3dad6e9f.png)

**Comment by tomolimo** [comment]
try may be with a more recent update

**Comment by tomolimo** [comment]
Are you using PHP 7 x86 or x64?

**Comment by satyan01** [comment]
php 7 x86

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/20000012/b4ecb4a4-a275-11e6-8529-95ec43830289.png)

**Comment by tomolimo** [comment]
could you update to latest version of PHP 7.0.12 ?

**Comment by tomolimo** [comment]
and may be x64?

**Comment by satyan01** [comment]
are you sure that is compatible ? x64

**Comment by tomolimo** [comment]
That's my current configuration on my Test server :)

**Comment by satyan01** [comment]
ok

**Comment by tomolimo** [comment]
use the NTS x64 package, and check that you have installed VC14 x64

**Comment by satyan01** [comment]
ok

**Comment by tomolimo** [comment]
be sure that you have installed the latest vc14: https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by satyan01** [comment]
I have installed and update php and vcredist and no error since 10:46.

**Comment by satyan01** [comment]
full x64
