### ISSUE TITLE
Tomolimo

### ISSUE THREAD

**Issue by satyan01** [tomolimo/timezones#5]
Hello

I don't know how to contact you,

Please, maybe you could do it and give me your opinion

http://glpi.userecho.com/topics/446-operation-master-plan/

**Comment by tomolimo** [comment]
Hello,
I saw that, and already asked my colleagues in charge of hardwares if they could be interested by this plugin :)
regards,
Tomlimo

**Comment by satyan01** [comment]
Thank you so much !
