### ISSUE TITLE
at each change in glpi db I have to launch dbupdate

### ISSUE THREAD

**Issue by satyan01** [tomolimo/timezones#6]
Hello

The plugin is disabled at each change of new table in glpi db,  I have to launch dbupdate to fix it

**Comment by tomolimo** [comment]
That's by design to prevent loss of the correct date / time. 
I've planned to improve this but it is not a priority as the db doesn't change every day...

**Comment by AircraftRu** [comment]
Confirm the problem. It would be good to fix it.

**Comment by tomolimo** [comment]
I've got already a beta version for this, and I plan to deliver it and the next weeks

**Comment by tomolimo** [comment]
Fixed by 96a598db79a2da2fdda12cf3d78a7c46f0ddebe7
See latest release: https://github.com/tomolimo/timezones/releases/tag/2.1.2
