### ISSUE TITLE
populate timezone on freebsd 10.3

### ISSUE THREAD

**Issue by da-sti** [tomolimo/timezones#8]
just installed the plugin on 
- 10.3-RELEASE FreeBSD 10.3-RELEASE #0 r297264: Fri Mar 25 02:10:02 UTC 2016
- GLPI 0.90.5

I get an error when I launch the command to populate the "mysql" database with time zones informations from the system
`mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql`

first I have to add -p so it ask for the root password
`ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)`

then I get this error
`ERROR 1406 (22001) at line 32148: Data too long for column 'Abbreviation' at row 1`

I don't see a file with 32148 lines.
The `zone.tab` file size is different from the one on linux ubuntu for example but the format seems similar

thanks
dasti

**Comment by tomolimo** [comment]
Hello,
This issue is not related to timezones plugin, but to your system+mySQL, and unfortunately, I cannot help you on this system :(.
Feel free to re-open this issue if you don't agree with this statement. 
Regards
Tomolimo
