### ISSUE TITLE
RU locale

### ISSUE THREAD

**Issue by AircraftRu** [tomolimo/timezones#9]
I translated. Please, add
[ru_RU.zip](https://github.com/tomolimo/timezones/files/713507/ru_RU.zip)

**Comment by AircraftRu** [comment]
I'm sorry. I corrected my mistakes. please add
[ru_RU.zip](https://github.com/tomolimo/timezones/files/713581/ru_RU.zip)

**Comment by tomolimo** [comment]
Thank you very much for this.
But next time could do a PR, instead posting a zip file?
Thank you,
regards,
Tomolimo
